### ISSUE TITLE
Language Toggle

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#154]
As a Spanish speaking BEARS site user, in order to understand BEARS site and find the benefits I might be eligible for, I would like to be able to change the language of the site from English to Spanish from anywhere within the site.

Acceptance Criteria:

- The user can click the "Espanol" button from anywhere within the BEARS site
- "Espanol" button switches BEARS site to Spanish language (#309  and #310 )
- When the BEARS site is switched to Spanish language, the "Espanol" button is replaced with "English" button
  - Clicking on "English" button switches the site to English language
- When the BEARS site is switched to Spanish language, USAGov logo is replaced with USAGov en Espanol logo
- When the BEARS site is switched to Spanish language, the buttons, components and all copy containers are responsive to accommodate different text length

Definition of Done:
- [x] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [ ] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)
