### ISSUE TITLE
Navigation translation

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#309]
As a Spanish speaking BEARS site user, in order to successfully navigate BEARS site, I would like all site navigation to be in Spanish language.

Assumptions:

- Navigation links and copy are translated to Spanish language (format?)

Acceptance Criteria:

- When the BEARS site is switched to Spanish language, BEARS site navigation links and copy are translated to Spanish language
  - BEARS site navigation includes: main nav, header, utility nav and copy, and footer nav

Definition of Done:
- [x] Code complete
- [x] Tests coverage is greater than team benchmark (90% goal)
- [x] Security scans passed
- [x] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Cross browser tested
- [x] Build process and deployment is automated and repeatable 
- [x] Load testing/performance testing 
- [x] Self Documentation whenever possible
- [x] Feature toggles if appropriate 
- [x] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] A11y tested by Meghan
- [x] PO approved (UX, usability, edge cases)

More details about each item can be find in [BEARS P4 DoD google doc](https://docs.google.com/document/d/118sdf54uF1vz-5pMvGodV8LRnrUJfjMbHcarCA8AS70/edit?usp=sharing)

[QA checklist](https://docs.google.com/document/d/1AUO-vg0t7DYgQsNouKtz4fFPwelBzZaDZMCkjmPQy0Y/edit?usp=sharing)
