### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/usagov-benefits-eligibility#392]
- [x] Check with Russell on notifying Digital Council about launch
- [x] ~Review [Digital.gov checklist](https://docs.google.com/spreadsheets/d/1up8HLxy8_2g9osv_K515osohuGG2PWWsALXoiX3BTns/edit?usp=sharing)~ (not needed)
- [x] Review internal checklist (in comment below)

**Comment by r-bartlett-gsa** [comment]
Jona’s website checklist


- [ ] Website - Post-launch
  - [ ] Request reindexation
  - [ ] New sitemap submitted
  - [ ] Search console verification
  - [ ] Link check
  - [ ] Update any hardcoded link references
- [ ] Website - Pre-launch
  - [ ] 301 plan
  - [ ] SEO
    - [ ] Open graph stuff
    - [ ] Metas
    - [ ] OG: image
  - [ ] Accessibility review
  - [ ] Forms submit and are delivered to email address
    - [ ] Add custom DOM events
    - [ ] Email sends and is delivered
    - [ ] Add Thank you page
  - [ ] Search.gov pointing to right profile ([search@support.digitalgov.gov](mailto:search@support.digitalgov.gov))
    - [ ] Question about subdomain
  - [ ] Google Analytics/Search Console
  - [ ] Wired into site
  - [ ] Cross browser testing
  - [ ] Screencaps of old site
  - [ ] Spider current (old) site, create XML sitemap
  - [ ] Internal review (TTS Comms, OGP, etc.)
  - [ ] Favicon
  - [ ] 404 page check
  - [ ] Thank you page copy - Qualtrics idea submission
- [ ] Team review
- [ ] Legal review
- [ ] Client review
- [ ] Go-live

**Comment by r-bartlett-gsa** [comment]
[Digital.gov resources](https://digital.gov/2022/01/13/go-live-checklist-for-federal-websites/)

**Comment by r-bartlett-gsa** [comment]
USAGov OG stuff

> Open Graph Check Results for: https://www.usa.gov/
> Meta Tags found:
> Tag	Content
> og:url	https://www.usa.gov/
> og:type	website
> og:title	Official Guide to Government Information and Services | USAGov
> og:description	USA.gov can help you start your search for government information by topic and agency.
> og:image	https://www.usa.gov/images/facebook_share_thumbnail.png
> og:image:secure_url	https://www.usa.gov/images/facebook_share_thumbnail.png

**Comment by fpigeonjr** [comment]
OG stuff added and merged

**Comment by lgarceau768** [comment]
Went over the performance reports, I was able to set up caching for our assets. But as for some of the other suggested changes, I was not able to compress the images any more, also the other reasons why our site is receiving a slight bad performance rating is because of the layout change but that is the loading of the content into our site. Also I think the performance of 370ns load time is good for our project.

**Comment by r-bartlett-gsa** [comment]
@lgarceau768 Thank you!!
