### ISSUE TITLE
make sure response matches available criteria (TODO from store/criteria.js)

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/usagov-benefits-eligibility#410]
# User Story

As a BEARS **developer**, in order to **clean up our code**, I would like **complete the `TODO` task or remove the `TODO` notation from the source** .

```javascript
// TODO: make sure the response matches one of the available criterion values
```
source: https://github.com/GSA/usagov-benefits-eligibility/blob/main/store/criteria.js#L13

Acceptance Criteria:

- [ ] task (make sure the response matches one of the available criterion values) is completed
OR:
- [ ] `TODO` notation is removed

Definition of Done:

- [ ] Code complete
- [ ] Tests coverage is greater than team benchmark (90% goal)
- [ ] Security scans passed
- [ ] Acceptance Criteria is met and it works as expected
- [ ] Accessibility tested
- [ ] Build process and deployment is automated and repeatable
- [ ] Load testing/performance testing
- [ ] Self Documentation whenever possible
- [ ] Feature toggles if appropriate
- [ ] Deployed to staging
- [ ] Usability testing
- [ ] PR approved / Peer reviewed
- [ ] PO approved
