### ISSUE TITLE
Translate Retirement and Disability

### ISSUE THREAD

**Issue by danny-englander** [GSA/usagov-benefits-eligibility#674]
### User Story

As a content editor, I need to translate the new `retirement` and `disability` pages in the mutli-life event version of the application. 

### Description

This issue and [corresponding PR](https://github.com/GSA/usagov-benefits-eligibility/pull/663) from Diego is dependent on [Multi-life event feature branch](https://github.com/GSA/usagov-benefits-eligibility/pull/661) going live into production. 

For the new beta footer that has the CrossSell component, we will need to translate the pages for `retirement` and `disability`.  Some of this work has started over in this branch: https://github.com/GSA/usagov-benefits-eligibility/tree/multi-life-event-2023-content with a draft PR here: [Translate Retirement and Disability (deprecated) ](https://github.com/GSA/usagov-benefits-eligibility/pull/663 )

### Preview environment pages that need translating
- https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023-content/disability/
- https://federalist-edd11e6f-8be2-4dc2-a85e-1782e0bcb08e.sites.pages.cloud.gov/preview/gsa/usagov-benefits-eligibility/multi-life-event-2023-content/es/retirement/

Note, when you commit code to the multi-life-event-2023-content as listed above, it will automatically push to cloud.gov and the changes will show after about 3- 6 minutes.  

### Definition of done

- [x] copy `/locales/en/life-events/disability.json` and put into `/locales/es/life-events/disability.json` and then translate to Spanish
- [x] copy `/locales/en/life-events/retirement.json` and put into `/locales/es/life-events/retirement.json` and then translate to Spanish
- [x] Add the `retirement` and `disability` routes for Spanish to `/locales/es.js` You can see the existing routes in  `/locales/en.js` and then copy them over ensuring to put es in the path, for example, `require("./en/life-events/disability.json"),` becomes `require("./es/life-events/disability.json"),` in `/locales/es.js`
- [x] Translate accordion titles and content. For example if you visit the page `/es/disability/` You will see that many things only have the field names and not translated content. The files for these will be under `/locales/en/benefits` and then you will need to create a corresponding file under `/locales/es/benefits`. 
- [ ] Translate anything else that only shows a field name on `retirement` and `disability` pages. See a developer for clarification with regard to these items if you are unsure where to find them

**Comment by diegocob** [comment]
Ok, @danny-englander, will get working on this and check with you before doing the first copy, to make sure I don't mess it up.

**Comment by diegocob** [comment]
Was able to do the first three items, couldn't find the accordion files and wanted clarification for the last point.

**Comment by danny-englander** [comment]
@diegocob ok, we will meet to discuss, thank you!
